# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-23 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='upload date')),
                ('upload', models.FileField(upload_to=b'adminfiles', verbose_name='file')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='description')),
                ('content_type', models.CharField(editable=False, max_length=100)),
                ('sub_type', models.CharField(editable=False, max_length=100)),
            ],
            options={
                'ordering': ['upload_date', 'title'],
                'verbose_name': 'file upload',
                'verbose_name_plural': 'file uploads',
            },
        ),
        migrations.CreateModel(
            name='FileUploadReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminfiles.FileUpload')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='fileuploadreference',
            unique_together=set([('upload', 'content_type', 'object_id')]),
        ),
    ]
